### ISSUE TITLE
Title font appears different in various browsers

### ISSUE THREAD

**Issue by kitsandkats** [ml-learning/elements#14]
In Chrome: 
<img width="863" alt="screen shot 2018-12-11 at 1 32 25 pm" src="https://user-images.githubusercontent.com/6548760/49821760-3b0dcc00-fd49-11e8-9de2-ae04428eb5ae.png">

In Firefox and Safari:
<img width="1393" alt="screen shot 2018-12-11 at 1 32 57 pm" src="https://user-images.githubusercontent.com/6548760/49821785-49f47e80-fd49-11e8-949f-0551b64412c6.png">

**Comment by vespertines** [comment]
https://github.com/ml-learning/elements/commit/5f0d9d04e8d742241200cca7a25b403fc7a23ca1
