### ISSUE TITLE
Experiment with placement of logo words on small screens

### ISSUE THREAD

**Issue by kitsandkats** [ml-learning/elements#21]
Some options we discussed:

1. Removing the text on small screens and just using the bracketed logo
2. Moving the the text from the right side back to the left side of the bottom screen (so same placement as for the large screen) -- this requires narrowing content containers
3. Having the "mit media lab" text appear only on hover over the logo brackets, though this might be confusing since hovering over the top part of the logo might make the text appear in the bottom left
4. We could also perhaps unstack the words "mit / media / lab " and have them appear all on one line?

I think option (1) might work if we also bring back loading screen idea with the logo "exploding" out into it's bracket placement on site load?

**Comment by kitsandkats** [comment]
@vespertines -- let me know what you're thinking here.

**Comment by vespertines** [comment]
https://github.com/ml-learning/elements/commit/a17d88d6920b4369ce5a4b307e75047c03f60426
