### ISSUE TITLE
Responsive styling right before mobile breakpoint is a bit wonky

### ISSUE THREAD

**Issue by kitsandkats** [ml-learning/elements#35]
See attached screenshot -- the images on the right seem like they are too small -- perhaps we should just break to single column a bit earlier. Also, please note that the link does not break properly and overflows from the left column into the right column.

<img width="963" alt="Screen Shot 2019-04-05 at 2 40 38 PM" src="https://user-images.githubusercontent.com/6548760/55649641-842ed380-57b1-11e9-94ef-94069fd2a346.png">

**Comment by vespertines** [comment]
https://github.com/ml-learning/science/commit/a85b3b785764dd41a47f4568b24e94c87f2de5f9
