### ISSUE TITLE
Constrain height of vertically oriented images on project pages

### ISSUE THREAD

**Issue by kitsandkats** [ml-learning/elements#39]
E.g. on this page https://learn.media.mit.edu/science/climate-cubesat-co-building/ -- the fourth photo down

There is a vertical-oriented photo that appears very large because of the new margins -- perhaps we need a max-height parameter?

**Comment by kitsandkats** [comment]
<img width="1332" alt="Screen Shot 2019-04-19 at 2 40 09 PM" src="https://user-images.githubusercontent.com/6548760/56438475-130f1600-62b1-11e9-8140-79f4df7b2dfa.png">

**Comment by vespertines** [comment]
62a06d586d2fad97748efdf7010908e06d046080

set 100% for max-width and 540px for max-height for images
