### ISSUE TITLE
Make links to external websites on project pages more prominent

### ISSUE THREAD

**Issue by kitsandkats** [ml-learning/elements#40]
We've gotten some feedback that it's a bit unclear that there are links out to external resources from each of the project pages -- we want to make sure that a user who comes to this site and gets excited about one of the projects can have a clear way to link out to that project's website and be able to get started.

Perhaps the link at the end of the first paragraph in the project page should be a button? or highlighted in the accent color? Also, can we make all the inline links bold and in their accent color? it's hard to tell that a lot of things that are links on the site are actually links!

**Comment by vespertines** [comment]
95901610883abf3b6845b9d01912e40055160e24
