### ISSUE TITLE
About page content restructuring

### ISSUE THREAD

**Issue by kitsandkats** [ml-learning/elements#6]
As it is right now, there is no longer a "ML Learning" section on the about page -- it is now all rolled into the first "Overview" section. However, it should be changed to the following:

First: Elements (no shape) and text up to "...feel more connected to their local ecosystems."

Second: *(new section)* "Elements is a collaborative Media Lab project from ML Learning, OpenAg, Open Ocean, and the Space Exploration Initiative. Each of our three elemental focus areas is based on current Media Lab research. Scroll on to learn more about the work of each initiative."

Third: ML Learning (purple triangle)
Fourth: OpenAg 
Fifth: Open Ocean
Sixth: Space Exploration

-- let me know if you have any questions about this! All the text is also in the Content document.

**Comment by vespertines** [comment]
https://github.com/ml-learning/elements/commit/d09c70780ea71870d3bc1eb2e6e7fd7750407011
